"""empty message

Revision ID: 5b7333be07b0
Revises: 396bbb2378b4
Create Date: 2022-05-10 17:13:35.513366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7333be07b0'
down_revision = '396bbb2378b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sa.TEXT(), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'totp_secret', schema='auth')
    # ### end Alembic commands ###
