# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\"\"\n\x0fGreetingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"%\n\x10GreetingResponse\x12\x11\n\tgreetings\x18\x01 \x01(\t29\n\tGreetings\x12,\n\x05Greet\x12\x10.GreetingRequest\x1a\x11.GreetingResponseb\x06proto3')



_GREETINGREQUEST = DESCRIPTOR.message_types_by_name['GreetingRequest']
_GREETINGRESPONSE = DESCRIPTOR.message_types_by_name['GreetingResponse']
GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGREQUEST,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:GreetingRequest)
  })
_sym_db.RegisterMessage(GreetingRequest)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGRESPONSE,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:GreetingResponse)
  })
_sym_db.RegisterMessage(GreetingResponse)

_GREETINGS = DESCRIPTOR.services_by_name['Greetings']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETINGREQUEST._serialized_start=21
  _GREETINGREQUEST._serialized_end=55
  _GREETINGRESPONSE._serialized_start=57
  _GREETINGRESPONSE._serialized_end=94
  _GREETINGS._serialized_start=96
  _GREETINGS._serialized_end=153
# @@protoc_insertion_point(module_scope)
