# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrole.proto\x12\x06rolepb\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\rTokenResponse\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\t\x12\x0f\n\x07refresh\x18\x02 \x01(\t\"\"\n\x10\x41uthorizeRequest\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\t\"\x1c\n\x0cRoleResponse\x12\x0c\n\x04role\x18\x01 \x01(\t\"6\n\x10RoleResponseList\x12\"\n\x04role\x18\x01 \x03(\x0b\x32\x14.rolepb.RoleResponse2\xc4\x01\n\x04Role\x12:\n\tgetAccess\x12\x14.rolepb.LoginRequest\x1a\x15.rolepb.TokenResponse\"\x00\x12;\n\x07getRole\x12\x18.rolepb.AuthorizeRequest\x1a\x14.rolepb.RoleResponse\"\x00\x12\x43\n\x0bgetRoleList\x12\x18.rolepb.AuthorizeRequest\x1a\x18.rolepb.RoleResponseList\"\x00\x62\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_TOKENRESPONSE = DESCRIPTOR.message_types_by_name['TokenResponse']
_AUTHORIZEREQUEST = DESCRIPTOR.message_types_by_name['AuthorizeRequest']
_ROLERESPONSE = DESCRIPTOR.message_types_by_name['RoleResponse']
_ROLERESPONSELIST = DESCRIPTOR.message_types_by_name['RoleResponseList']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'role_pb2'
  # @@protoc_insertion_point(class_scope:rolepb.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

TokenResponse = _reflection.GeneratedProtocolMessageType('TokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOKENRESPONSE,
  '__module__' : 'role_pb2'
  # @@protoc_insertion_point(class_scope:rolepb.TokenResponse)
  })
_sym_db.RegisterMessage(TokenResponse)

AuthorizeRequest = _reflection.GeneratedProtocolMessageType('AuthorizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZEREQUEST,
  '__module__' : 'role_pb2'
  # @@protoc_insertion_point(class_scope:rolepb.AuthorizeRequest)
  })
_sym_db.RegisterMessage(AuthorizeRequest)

RoleResponse = _reflection.GeneratedProtocolMessageType('RoleResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROLERESPONSE,
  '__module__' : 'role_pb2'
  # @@protoc_insertion_point(class_scope:rolepb.RoleResponse)
  })
_sym_db.RegisterMessage(RoleResponse)

RoleResponseList = _reflection.GeneratedProtocolMessageType('RoleResponseList', (_message.Message,), {
  'DESCRIPTOR' : _ROLERESPONSELIST,
  '__module__' : 'role_pb2'
  # @@protoc_insertion_point(class_scope:rolepb.RoleResponseList)
  })
_sym_db.RegisterMessage(RoleResponseList)

_ROLE = DESCRIPTOR.services_by_name['Role']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=22
  _LOGINREQUEST._serialized_end=69
  _TOKENRESPONSE._serialized_start=71
  _TOKENRESPONSE._serialized_end=119
  _AUTHORIZEREQUEST._serialized_start=121
  _AUTHORIZEREQUEST._serialized_end=155
  _ROLERESPONSE._serialized_start=157
  _ROLERESPONSE._serialized_end=185
  _ROLERESPONSELIST._serialized_start=187
  _ROLERESPONSELIST._serialized_end=241
  _ROLE._serialized_start=244
  _ROLE._serialized_end=440
# @@protoc_insertion_point(module_scope)
